name = "sveltekit-passkeys"
compatibility_date = "2024-12-08"

main = "./.cloudflare/worker.js"

site.bucket = "./.cloudflare/public"

build.command = "bun run build"

compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "sveltekit-passkeys"
database_id = "9fcc4ee4-a6e3-4934-a60c-d9aa6ec276c1"

[[kv_namespaces]]
binding = "session"
id = "28c9afa44fb64f3290271107d85e05f5"
